triggerListURL = 'http://www.shahmoradi.org/ICP2017F/homework/5-problems/triggers.txt';
TriggerList = webread(triggerListURL);
TriggerList = strsplit( TriggerList, '\n');
figure(); hold on; box on;
eventCounter = 0; 
for i=1:length(TriggerList)
    disp(['Plotting data from file number: ', num2str(i)]);
    if ~isempty(data{i}) && all(data{i}(:,2)<0)
        eventCounter = eventCounter + 1;
        scatter( exp(data{i}(:,2))...
            , data{i}(:,1) ...
            , 1 ...
            , 'MarkerFaceColor', 'red' ...
            , 'MarkerEdgeColor', 'red' ...
            , 'MarkerFaceAlpha', .01 ...
            , 'MarkerEdgeAlpha', .01 ...
            );
    end
end
set( gca ...
    , 'xscale','log' ...
    , 'yscale','log' ...
    );
xlabel( 'Fluence [ ergs/cm^2 ]' ...
    , 'interpreter', 'tex' ...
    , 'fontsize', 12 ...
    );
ylabel( 'E_{peak}' ...
    , 'interpreter', 'tex' ...
    , 'fontsize', 12 ...
    );
title( ['Plot of E_{peak} vs. Fluence for ', num2str(eventCounter),
    ' Swift GRB events' ] ...
    , 'fontsize', 12 ...
    );
saveas( gcf ...
    , 'SwiftDataPlot.png' ...
    );
    
        
